version: "3.8"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: duplo_raincloud_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    restart: always
  app:
    image: duplo_raincloud
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - NODE_ENV=test
      - OPEN_METEO_BASE_URL=https://api.open-meteo.com/v1
      - MONGO_URI=mongodb://root:example@mongodb:27017/
volumes:
  mongodb_data:
